apiVersion: apps/v1
kind: Deployment

metadata:
  name: dido-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: dido-backend

  template:
    metadata:
      labels:
        app: dido-backend

    spec:
      containers:
      - name: backend

        image: swap2502/dido-backend:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        envFrom:
        - configMapRef:
            name: dido-config

        - secretRef:
            name: dido-secret

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5