name: DIDO CI/CD

on:
  push:
    branches:
      - main

jobs:

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: npm run build

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: npm run build

  docker:

    needs:
      - backend
      - frontend

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Backend Image
        run: |
          docker build \
          -t swap2502/dido-backend:latest \
          ./backend

      - name: Push Backend Image
        run: |
          docker push \
          swap2502/dido-backend:latest

      - name: Build Frontend Image
        run: |
          docker build \
          -t swap2502/dido-frontend:latest \
          ./frontend

      - name: Push Frontend Image
        run: |
          docker push \
          swap2502/dido-frontend:latest